repo:
  public: go-sdk-common
  private: go-sdk-common-private

releasableBranches:
  - name: v1

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-sdk-common
    description: documentation
