repo:
  public: go-sdk-common
  private: go-sdk-common-private

releasableBranches:
  - name: v1
    description: 1.x - for Go SDK 4.x

publications:
  - url: https://godoc.org/gopkg.in/launchdarkly/go-sdk-common.v1
    description: documentation
