repo:
  public: go-server-sdk-core
  private: go-server-sdk-core-private

releasableBranches:
  - name: v1

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-server-sdk-core
    description: documentation
